CREATE DATABASE  Assignment1;

use  Assignment1;

CREATE TABLE info(
SERIAL_NO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(250),
AGE INT(12), 
EMAIL VARCHAR(250),
CONTACT VARCHAR(12), 
COURSE VARCHAR(250) 
);
 SELECT * FROM info; 
INSERT INTO info VALUES (NULL, "shoaib", "20", "S@GMAIL.COM",0 , "CPISM");
INSERT INTO info VALUES (NULL, "yousuf", "20", "y@GMAIL.COM",03 ,"CPISM");
INSERT INTO info VALUES (NULL, "muneeb", "20", "m@GMAIL.COM",031 ,"CPISM");
INSERT INTO info VALUES (NULL, "khuzaima", "20", "k@GMAIL.COM",0318 ,"CPISM");
INSERT INTO info VALUES (NULL, "yaha", "20", "y@GMAIL.COM",0318 ,"CPISM");
INSERT INTO info VALUES (NULL, "syed", "20", "S@GMAIL.COM",0 , "CPISM");
INSERT INTO info VALUES (NULL, "mazz", "20", "m@GMAIL.COM",03 ,"CPISM");
INSERT INTO info VALUES (NULL, "muqasid", "20", "m@GMAIL.COM",031 ,"CPISM");
INSERT INTO info VALUES (NULL, "katen", "20", "k@GMAIL.COM",0318 ,"CPISM");
INSERT INTO info VALUES (NULL, "afzal", "20", "a@GMAIL.COM",0318 ,"CPISM");
INSERT INTO info VALUES (NULL, "syed", "20", "S@GMAIL.COM",0 , "CPISM");
INSERT INTO info VALUES (NULL, "zain", "20", "z@GMAIL.COM",03 ,"CPISM");
INSERT INTO info VALUES (NULL, "mudasir", "20", "m@GMAIL.COM",031 ,"CPISM");
INSERT INTO info VALUES (NULL, "ali", "20", "a@GMAIL.COM",0318 ,"CPISM");
INSERT INTO info VALUES (NULL, "maqsood", "20", "m@GMAIL.COM",0318 ,"CPISM");
INSERT INTO info VALUES (NULL, "shanzaib", "20", "S@GMAIL.COM",0 , "CPISM");
INSERT INTO info VALUES (NULL, "janzaib", "20", "j@GMAIL.COM",03 ,"CPISM");
INSERT INTO info VALUES (NULL, "ghufran", "20", "g@GMAIL.COM",031 ,"CPISM");
INSERT INTO info VALUES (NULL, "dawood", "20", "d@GMAIL.COM",0318 ,"CPISM");
INSERT INTO info VALUES (NULL, "basit", "20", "b@GMAIL.COM",0318 ,"CPISM");


INSERT INTO info ( NAME )VALUES ("adeel" );
INSERT INTO info ( NAME )VALUES ("muzalmil");
INSERT INTO info ( NAME )VALUES ("faisal" );
INSERT INTO info ( NAME )VALUES ("saif");
INSERT INTO info ( NAME )VALUES ("bilal");
INSERT INTO info ( NAME )VALUES ("mujahid" );
INSERT INTO info ( NAME )VALUES ("aman");
INSERT INTO info ( NAME )VALUES ("muhammad ali");
INSERT INTO info ( NAME )VALUES ("aqib" );
INSERT INTO info ( NAME )VALUES ("hasnain");


INSERT INTO info (NAME,EMAIL, AGE)VALUES ( "SHAN","S@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ( "AZAN","a@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ( "usman","u@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ("hamza","h@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ("usama","u@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ("waseem","w@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ( "arslan","a@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ( "sanaullah","S@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ( "Sharik","S@GMAIL.COM", 20 );
INSERT INTO info (NAME,EMAIL, AGE)VALUES ("mosin","m@GMAIL.COM", 20 );


UPDATE info SET   AGE= "22",EMAIL= "a@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =21;
UPDATE info SET   AGE= "22",EMAIL= "m@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =22;
UPDATE info SET   AGE= "22",EMAIL= "f@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =23;
UPDATE info SET   AGE= "22",EMAIL= "s@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =24;
UPDATE info SET   AGE= "22",EMAIL= "b@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =25;
UPDATE info SET   AGE= "22",EMAIL= "m@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =26;
UPDATE info SET   AGE= "22",EMAIL= "a@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =27;
UPDATE info SET   AGE= "22",EMAIL= "m@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =28;
UPDATE info SET   AGE= "22",EMAIL= "a@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =29;
UPDATE info SET   AGE= "22",EMAIL= "h@gmail.com" , CONTACT = "0022", COURSE ="CPISM"  WHERE SERIAL_NO =30;


DELETE FROM info WHERE SERIAL_NO =21;
DELETE FROM info WHERE SERIAL_NO =22;
DELETE FROM info WHERE SERIAL_NO =23;
DELETE FROM info WHERE SERIAL_NO =24;
DELETE FROM info WHERE SERIAL_NO =25;
DELETE FROM info WHERE SERIAL_NO =26;
DELETE FROM info WHERE SERIAL_NO =27;
DELETE FROM info WHERE SERIAL_NO =28;
DELETE FROM info WHERE SERIAL_NO =29;
DELETE FROM info WHERE SERIAL_NO =30;
DELETE FROM info WHERE SERIAL_NO =31;
DELETE FROM info WHERE SERIAL_NO =32;
DELETE FROM info WHERE SERIAL_NO =33;
DELETE FROM info WHERE SERIAL_NO =34;
DELETE FROM info WHERE SERIAL_NO =35;
DELETE FROM info WHERE SERIAL_NO =36;
DELETE FROM info WHERE SERIAL_NO =37;
DELETE FROM info WHERE SERIAL_NO =38;
DELETE FROM info WHERE SERIAL_NO =39;
DELETE FROM info WHERE SERIAL_NO =40;


