CREATE DATABASE SHAHEEN_E_IQBAL;

USE SHAHEEN_E_IQBAL;

CREATE TABLE STUDENT (
ID INT ,
NAME VARCHAR(250),
AGE INT
);

SELECT * FROM STUDENT; 

ALTER TABLE STUDENT ADD DOB DATE ,ADD GENDER VARCHAR(250) , ADD COURSE VARCHAR(250) , ADD FACULTY VARCHAR(250);

ALTER TABLE STUDENT DROP DOB  ,DROP GENDER  , DROP COURSE  ,DROP FACULTY ;

ALTER TABLE STUDENT modify COLUMN ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL ;

