CREATE DATABASE A09;

USE A09;

CREATE TABLE STUDENT (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(250),
    COURSE VARCHAR(250)
);

SELECT 
    *
FROM
    STUDENT; 

INSERT INTO STUDENT VALUES (NULL, "AFFAN", "OFFICE");
INSERT INTO STUDENT VALUES (NULL, "ANAS", "CPISM");
INSERT INTO STUDENT VALUES (NULL, "AHMED", "SQL");
INSERT INTO STUDENT VALUES (NULL, "HARRYSON", "APPDEVELOPMENT");
INSERT INTO STUDENT VALUES (NULL, "LAIBA", "MACHINE LEARNING");
INSERT INTO STUDENT VALUES (NULL, "MISBAH", "DATA SCIENCE");
INSERT INTO STUDENT VALUES (NULL, "OSAMA", "PHP");
INSERT INTO STUDENT VALUES (NULL, "HAMZA", "PYTHON");
INSERT INTO STUDENT VALUES (NULL, "ZAID", "ATIFICIAL INTELLIGENCE");
INSERT INTO STUDENT VALUES (NULL, "HAROON", "ETHICAL HACKING");

DELIMITER //
CREATE PROCEDURE SelectData()
BEGIN 
  SELECT * FROM STUDENT;
END
// 
DELIMITER;

CALL SelectData();

DELIMITER //
CREATE PROCEDURE INSERTDATA(STDNAME VARCHAR(250), CRSE VARCHAR(250))
BEGIN
  INSERT INTO STUDENT (NAME, COURSE) VALUES (STDNAME, CRSE);
END
//

CALL INSERTDATA("YOUSUF", "SQL");
CALL INSERTDATA("SHOAIB", "HTML");
CALL INSERTDATA("KHUZAIMA", "PYTHON");
CALL INSERTDATA("MUNEEB", "PYTHON");

DELIMITER //
CREATE PROCEDURE DELETEDATA(STDNAME VARCHAR(250))
BEGIN 
  DELETE FROM STUDENT WHERE NAME = STDNAME;
END 
//

CALL DELETEDATA("AFFAN");
CALL DELETEDATA("AHMED");
CALL DELETEDATA("LAIBA");
CALL DELETEDATA("OSAMA");

DELIMITER //
CREATE PROCEDURE SEARCHBYNAME(STDNAME VARCHAR(250))
BEGIN
  SELECT * FROM STUDENT WHERE NAME = STDNAME;
END
//

CALL SEARCHBYNAME("Yousuf");
CALL SEARCHBYNAME("Khuzaima");
CALL SEARCHBYNAME("Shoaib");
CALL SEARCHBYNAME("Muneeb");

DELIMITER //

CREATE PROCEDURE UPDATEDATA(STDNAME VARCHAR(250), CRSE VARCHAR(250), STDNTNAME VARCHAR(250))
BEGIN
  UPDATE STUDENT SET NAME = STDNAME, COURSE = CRSE WHERE NAME = STDNTNAME;
END
//

CALL UPDATEDATA( "AHMED", "SQL", "Zubair");
CALL UPDATEDATA( "HAROON", "ETHICAL HACKING", "Abrar");
CALL UPDATEDATA("MUNEEB", "PYTHON", "Ayesha");